// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDABPaIuEr6FqESyHLo7YU3dXMj1jXVx3A',
    appId: '1:243721627371:web:dcc467d7bcdf3a5fa300ae',
    messagingSenderId: '243721627371',
    projectId: 'employee-management-7677b',
    authDomain: 'employee-management-7677b.firebaseapp.com',
    storageBucket: 'employee-management-7677b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCstS14YuLnY-JJaLC0cB-JsdJ85XgpCZo',
    appId: '1:243721627371:android:2bcfbacf62110bb6a300ae',
    messagingSenderId: '243721627371',
    projectId: 'employee-management-7677b',
    storageBucket: 'employee-management-7677b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8cVM-Ibtkx1wYl2q8kT5pF_isJPF64T4',
    appId: '1:243721627371:ios:d23444c1cfe302afa300ae',
    messagingSenderId: '243721627371',
    projectId: 'employee-management-7677b',
    storageBucket: 'employee-management-7677b.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8cVM-Ibtkx1wYl2q8kT5pF_isJPF64T4',
    appId: '1:243721627371:ios:d23444c1cfe302afa300ae',
    messagingSenderId: '243721627371',
    projectId: 'employee-management-7677b',
    storageBucket: 'employee-management-7677b.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDABPaIuEr6FqESyHLo7YU3dXMj1jXVx3A',
    appId: '1:243721627371:web:7d102bbefd6c6244a300ae',
    messagingSenderId: '243721627371',
    projectId: 'employee-management-7677b',
    authDomain: 'employee-management-7677b.firebaseapp.com',
    storageBucket: 'employee-management-7677b.firebasestorage.app',
  );
}
